services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
#    labels:
#      - homepage.group=Server - Networking
#      - homepage.name=Nginx Proxy Manager
#      - homepage.href=http://192.168.1.102:81
#      - homepage.description=Proxy GUI
