services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/portainer-compose-unpacker/stacks/nginx-proxy-manager/nginx-proxy-manager/data:/data
      - /mnt/portainer-compose-unpacker/stacks/nginx-proxy-manager/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
#    labels:
#      - homepage.group=Server - Networking
#      - homepage.name=Nginx Proxy Manager
#      - homepage.href=http://192.168.1.102:81
#      - homepage.description=Proxy GUI
